# Замените "your-mj-worker-name" на уникальное имя для вашего воркера.
# Оно будет частью URL: your-mj-worker-name.your-account.workers.dev
name = "your-mj-worker-name"

# Указывает на главный файл воркера в папке src
main = "./worker.js"

# Важно для стабильности API. Используйте актуальную дату.
compatibility_date = "2024-03-18" # Или более новая

# --- Конфигурация Workers AI ---
# Необходима для доступа к платформе AI
[ai]
# Создает переменную env.AI в вашем коде воркера
binding = "AI"

# --- Переменные окружения и Секреты ---
# Мы будем использовать секрет для API-ключа доступа к нашему эндпоинту
# Устанавливается через: npx wrangler secret put API_KEY
# [vars]
# API_KEY = "установлен через secret"
